Rename @3cities/react-app -> @3cities/interface

diff --git a/.github/actions/build-prod/action.yml b/.github/actions/build-prod/action.yml
--- a/.github/actions/build-prod/action.yml
+++ b/.github/actions/build-prod/action.yml
@@ -39,8 +39,8 @@ runs:
         REACT_APP_WALLETCONNECT_PROJECT_ID: ${{ inputs.walletConnectProjectId }}
     # uncomment this step to test source map detection and trigger a workflow failure:
     # - name: Test source map detection
-    #   run: touch ./packages/react-app/build/static/fake-source.map
+    #   run: touch ./packages/interface/build/static/fake-source.map
     #   shell: bash
     - name: Ensure sourcemaps are disabled in deployments
-      run: (find ./packages/react-app/build | grep "map$" || exit 0 && (echo "unexpectedly found a source map in the build directory, failing build" && exit 1);)
+      run: (find ./packages/interface/build | grep "map$" || exit 0 && (echo "unexpectedly found a source map in the build directory, failing build" && exit 1);)
       shell: bash
